### ISSUE TITLE
Thinking about Google Auth

### ISSUE THREAD

**Issue by sounmind** [calendar-analytics/calendar-analytics#2]

**Comment by MclPio** [comment]
Will work on:
✓ install gems: [figaro](https://github.com/laserlemon/figaro)
✓ register app with google developer, selected sensitive and nonsensitive scopes, added test users.
1. Implement basic flow: 
    1. User sign in if cookie storage tokens expired or do not exist. 
    1. store refresh and access tokens in cookie storage after successful sign-in. 
    3. server returns calendar list as a test or any other obj from calendar api.
1. Update README with gem install instruction

**Comment by MclPio** [comment]
This article is relevant to implement sign in:
https://nicholusmuwonge.medium.com/social-login-with-react-rails-api-devise-auth-token-b938d89f85ca

**Comment by MclPio** [comment]
studying this [playlist](https://youtube.com/playlist?list=PLgYiyoyNPrv_yNp5Pzsx0A3gQ8-tfg66j&si=dsKJnf9g4Cmej7bx) to see how I can implement authentication.

**Comment by MclPio** [comment]
This could be the solution:
To design your app with Google OAuth for calendar access using Rails API and React, here's a recommended approach:

### **Backend (Rails API Only):**
1. **OmniAuth Setup:**
   - Use the `omniauth-google-oauth2` gem to handle OAuth flow.
   - Configure the OmniAuth middleware in your Rails API to handle Google OAuth callbacks. This middleware will redirect to your frontend after successful authentication.

2. **Google OAuth Controller:**
   - Create a `SessionsController` to handle the Google OAuth callback.
   - Upon receiving the callback, extract the tokens (access and refresh tokens) from the OmniAuth hash.
   - Serialize the tokens and send them to the frontend via a JSON response.
   - **Security Tip:** Use HTTPS to ensure tokens are securely transmitted.

3. **No Database Storage:**
   - Since you don’t need to store user data in the backend, the tokens won’t be saved in a database. The backend only facilitates the OAuth flow and token retrieval.

### **Frontend (React):**
1. **OAuth Flow:**
   - Initiate the OAuth flow by directing users to the backend’s OmniAuth URL when they choose to log in with Google.
   - On successful login, the backend will redirect or send back a JSON response containing the tokens.

2. **Store Tokens in Cookies:**
   - Use `js-cookie` or a similar library to store the tokens in secure, HTTP-only cookies.
   - Ensure that the access token and refresh token are stored securely. Use attributes like `secure`, `httpOnly`, and `sameSite` to protect the tokens.

3. **API Requests:**
   - For requests that need to access Google Calendar data, include the access token stored in the cookies in your request headers.

4. **Token Refreshing:**
   - Google’s access tokens expire after a short period, so you’ll need to handle token refreshing using the refresh token stored in the cookies.
   - Set up an interceptor (e.g., in Axios) to detect expired tokens, then make a request to your Rails API to refresh the token using the refresh token.

### **Token Handling Workflow:**
1. **User Logs In:**
   - User clicks a “Sign in with Google” button on your React app.
   - Redirects to your Rails API, which handles the OAuth request.
   - After authentication, tokens are sent to your React app and stored in cookies.

2. **API Interaction:**
   - Your React app makes requests to the Google Calendar API, including the access token from the cookies.
   - If the access token is expired, the refresh token is used to obtain a new access token.

3. **Logout:**
   - Clear the cookies storing the tokens upon logout to ensure the user is fully signed out.

### **Security Considerations:**
- **HTTPS:** Ensure your app is served over HTTPS to protect token integrity.
- **Cookie Security:** Set cookies with `secure`, `httpOnly`, and `sameSite` attributes to prevent XSS and CSRF attacks.

This setup will enable your users to authenticate with Google and securely interact with their calendar data using tokens stored in the browser without needing user accounts on the backend.
